---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend-db-google
      location: local
  parameters:
    namespace: production
    image: docker.io/vfarcic/silly-demo:1.1.3
    port: 8080
    host: silly-demo.34.23.192.11.nip.io
    db:
      version: "13"
      size: small
