apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: silly-demo-password
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: google
  target:
    name: silly-demo-password
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: production-postgresql
