# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: silly-demo-password
# data:
#   password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      provider: google-official
      db: postgresql
  parameters:
    version: "13"
    size: small
