name: Create App
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "App name"
        type: string
        default: "idp-demo"
      repo-user:
        required: true
        description: "Repository user"
        type: string
        default: "vfarcic"
      repo-name:
        required: true
        description: "Repository name"
        type: string
        default: "idp-demo-app"
      type:
        required: true
        description: "App type (backend)"
        type: string
        default: "backend"
      environment:
        required: true
        description: "Environment to deploy app to (production, staging, development)"
        type: string
        default: "production"
      port:
        required: true
        description: "The port of the application"
        type: string
        default: "8080"
      host:
        required: false
        description: "The host of the application"
        type: string
        default: "acme.com"
      has-db:
        required: true
        description: "Does the app have a database?"
        type: boolean
        default: true
      db-version:
        required: false
        description: "The database version"
        type: string
        default: "13"
      db-size:
        required: false
        description: "The database size (small, medium, large)"
        type: string
        default: "small"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Create Argo CD App
        run: |
          chmod +x scripts/create-argocd-app.sh
          ./scripts/create-argocd-app.sh ${{ inputs.name }} ${{ inputs.repo-user }} ${{ inputs.repo-name }} ${{ inputs.environment }}
      - name: Commit changes
        run: |
          git config --local user.email "viktor@farcic.com"
          git config --local user.name "vfarcic"
          git add .
          git commit -m "Deploy ${{ inputs.name }} to ${{ inputs.environment }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
  # report-deployment:
  #   name: Report new deployment Entity
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Extract SHA short
  #       run: echo "SHA_SHORT=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
  #     - name: "Report deployment Entity to port 🚢"
  #       uses: port-labs/port-github-action@v1
  #       with:
  #         clientId: ${{ secrets.PORT_CLIENT_ID }}
  #         clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
  #         identifier: ${{ inputs.service }}-${{ inputs.environment }}-${{ env.SHA_SHORT }}
  #         blueprint: deployment
  #         properties: |
  #           {
  #              "jobUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
  #              "deployingUser": "${{ github.actor }}",
  #              "imageTag": "latest",
  #              "commitSha": "${{ env.SHA_SHORT }}"
  #           }
  #         runId: "${{fromJson(inputs.port_payload).context.runId}}"